import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ourFileRouter } from "./api/uploadthing/core";
import { extractRouterConfig } from "uploadthing/server";
import AuthProvider from "@/components/Providers/auth.provider";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { ModalProvider } from "@/components/Providers/modal.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const myFont = localFont({
  src: "../public/fonts/mona-sans-cufonfonts/regular.ttf",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={myFont.className}>
        <AuthProvider>
          <ModalProvider />
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
